{% set name = "dist-matrix" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dist_matrix-{{ version }}.tar.gz
  sha256: 73a51836bc7e1709a5432103a006541c4d73af48732d4e71c75b4eefa5f45e9a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - flit
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - numba >=0.53.1

test:
  imports:
    - dist_matrix
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Predict materials properties using only the composition information.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sgbaird
